spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springdb?useSL=false
      username: root
      password: admin
   application: 
         name: emp-data-service
         
eureka: 
     Client: 
       register-with-eureka: true
       service-url:
         defaultzone: http://localhost:8761/eureka/      